function Dog(name, age) {
    this.name = name;
    this.age = age;
    this.image_alt = "A cute golden puppy running towards you in the fall";
    this.image = "Images/cristian-castillo-73pyV0JJOmE-unsplash.jpg";
  }

  function Cat(name, age) {
    this.name = name;
    this.age = age;
    this.image_alt = "A grey cat";
    this.image = "Images/cristian-castillo-73pyV0JJOmE-unsplash.jpg";
  }

  function Elephant(name, age) {
    this.name = name; 
    this.age = age; 
    this.image_alt = "A gaggle of elephants"; 
    this.image = "Images/matthew-spiteri-WfZ4WCuNtlg-unsplash.jpg";
  }

  let animals = [new Cat(), new Dog(), new Elephant]; //creating a new array that holds new instances of each animal object
  let names = ["Luna", "Nellie", "Gumbo"]; // creating an array holding values for the name values above

  function getRandomIndex(maxIndex) { //Function gets an array index randomly from 0 to max index
    return Math.floor(Math.random() * maxIndex);
  }

  function generateRandomName() { //creates a random name from the list of names
    let randomIdx = getRandomIndex(names.length); // creating a variable and setting it to pull random index out of the whole array (names.length)
    return names[randomIdx]; //return names array value at that random index
  }

  function generateRandomAge() {
    return getRandomIndex(5); 
  }

  function generateRandomAnimal() {
   let randomIdx = getRandomIndex(animals.length); //calling random index generator and saying only pull from the length of animals array 
    let randomAnimal = animals[randomIdx];

    if (randomAnimal instanceof Cat) { // if this variable is Cat
      return new Cat(generateRandomName(), generateRandomAge()); //Return the array object with the values generated by these two functions for age and name
    }

    else if (randomAnimal instanceof Dog) {
      return new Dog(generateRandomName(), generateRandomAge()); 
    }

    else if (randomAnimal instanceof Elephant) {
      return new Elephant(generateRandomName(), generateRandomAge()); 
    }
  }

  function onLoad() {
    var animal = generateRandomAnimal(); 
    console.log(animal)
    document.getElementById("animal-properties").textContent = animal.name + "  " + animal.age + "years old";
    let imageTag = document.getElementById("animal-img");
    imageTag.setAttribute("src", animal.image);
    imageTag.setAttribute("alt", animal.image_alt);
  }